server:
  port: 9999
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
    database: 0




mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
